### PR TITLE
Fix references to the old tdaf-box name

### PR DESCRIPTION
**Pull request by JoseAntonioRodriguez**

### CODE REVIEW

**Comment by dlozlla** [comment]
LGTM but there are still pending issues in this regard for the portal. Let's use this PR to close issue #27

**Comment by labajo** [comment]
Solve #27

**Comment by labajo** [comment]
I will add a commit with the portal modifications.

**Comment by dlozlla** [comment]
Juan, there are conflicts, can you solve them.

**Comment by dlozlla** [comment]
LGTM

**Pull request merged**
